/* Tonninyira: discreet admin entry. No admin signup is exposed. */
(function(){
  'use strict';
  const URL='https://alxzmjgepftohwpqibmn.supabase.co';
  const KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFseHptamdlcGZ0b2h3cHFpYm1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU5OTg1NDQsImV4cCI6MjEwMTU3NDU0NH0.YvFQhCqL6spINPsyLs7lf7z5wxtnfi4U893ydWLXEaA';
  const sb=window.supabase.createClient(URL,KEY);
  const ADMIN_EMAIL='cuepointe@gmail.com';
  const ADMIN_NAME='Admin';
  function addStyles(){if(document.getElementById('tn-admin-access-style'))return;const s=document.createElement('style');s.id='tn-admin-access-style';s.textContent=`
    .tn-admin-access{font-size:8px!important;line-height:1;color:rgba(243,232,216,.22)!important;text-decoration:none!important;letter-spacing:.6px;cursor:pointer;margin-left:6px;background:none;border:0;padding:2px 3px}.tn-admin-access:hover{color:rgba(243,232,216,.55)!important}
    .tn-admin-modal{position:fixed;inset:0;z-index:12000;background:rgba(0,0,0,.78);display:grid;place-items:end center}.tn-admin-sheet{width:min(420px,100%);background:#1c1410;color:#f3e8d8;border:1px solid rgba(243,232,216,.1);border-radius:20px 20px 0 0;padding:20px 16px 24px}.tn-admin-input{width:100%;padding:13px;border-radius:10px;border:1px solid rgba(243,232,216,.14);background:#2a1f19;color:#f3e8d8;font:inherit;margin-top:6px}.tn-admin-submit{width:100%;padding:13px;border:0;border-radius:10px;background:#e23f25;color:#f3e8d8;font-weight:900;cursor:pointer;margin-top:14px}.tn-admin-msg{min-height:20px;color:#ffb0a5;font-size:12px;margin-top:8px}
  `;document.head.appendChild(s)}
  function close(){document.getElementById('tn-admin-modal')?.remove()}
  async function isAuthorized(uid){const {data:p}=await sb.from('profiles').select('role').eq('id',uid).maybeSingle();return p?.role==='admin'||p?.role==='staff'}
  async function open(){addStyles();const {data:{user}}=await sb.auth.getUser();if(user&&await isAuthorized(user.id)){location.href='./admin-control-tower.html';return}const m=document.createElement('div');m.id='tn-admin-modal';m.className='tn-admin-modal';m.innerHTML=`<div class="tn-admin-sheet"><div style="display:flex;justify-content:space-between;align-items:start"><div><div style="font-size:10px;letter-spacing:1.5px;color:#f5b400;font-weight:900">TONNINYIRA</div><h2 style="margin:4px 0 0;font:700 24px 'Work Sans',sans-serif">Admin sign in</h2></div><button id="tnAdminClose" style="background:none;border:0;color:#f3e8d8;font-size:26px;cursor:pointer">×</button></div><p style="color:#9c897a;font-size:12px;line-height:1.5">Restricted administrator access. There is no admin account creation here.</p><label style="font-size:12px;font-weight:800">Admin name</label><input id="tnAdminName" class="tn-admin-input" autocomplete="username" value="Admin"><label style="display:block;margin-top:12px;font-size:12px;font-weight:800">Password</label><input id="tnAdminPassword" class="tn-admin-input" type="password" autocomplete="current-password" placeholder="Enter admin password"><button id="tnAdminSubmit" class="tn-admin-submit">Sign in</button><div id="tnAdminMsg" class="tn-admin-msg"></div></div>`;document.body.appendChild(m);m.querySelector('#tnAdminClose').onclick=close;m.addEventListener('click',e=>{if(e.target===m)close()});m.querySelector('#tnAdminSubmit').onclick=async()=>{const name=m.querySelector('#tnAdminName').value.trim(),password=m.querySelector('#tnAdminPassword').value,msg=m.querySelector('#tnAdminMsg'),b=m.querySelector('#tnAdminSubmit');if(name.toLowerCase()!==ADMIN_NAME.toLowerCase()){msg.textContent='Administrator account not recognized.';return}if(!password){msg.textContent='Enter the admin password.';return}b.disabled=true;b.textContent='Signing in…';const r=await sb.auth.signInWithPassword({email:ADMIN_EMAIL,password});if(r.error){b.disabled=false;b.textContent='Sign in';msg.textContent='Admin sign-in failed. Check the name and password.';return}if(!(await isAuthorized(r.data.user.id))){await sb.auth.signOut({scope:'local'});b.disabled=false;b.textContent='Sign in';msg.textContent='This account is not authorized for administration.';return}location.href='./admin-control-tower.html'};
  }
  function boot(){addStyles();let host=document.querySelector('footer');if(!host){host=document.body}if(document.getElementById('tn-admin-access'))return;const b=document.createElement('button');b.id='tn-admin-access';b.className='tn-admin-access';b.textContent='Admin';b.title='Restricted';b.onclick=open;host.appendChild(b)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setTimeout(boot,1200);window.tnOpenAdminLogin=open;
})();
